var annotated_dup =
[
    [ "rtype", "namespacertype.html", [
      [ "components", "namespacertype_1_1components.html", [
        [ "ActualPlayer", "structrtype_1_1components_1_1ActualPlayer.html", "structrtype_1_1components_1_1ActualPlayer" ],
        [ "AiShoot", "structrtype_1_1components_1_1AiShoot.html", "structrtype_1_1components_1_1AiShoot" ],
        [ "Animation", "structrtype_1_1components_1_1Animation.html", "structrtype_1_1components_1_1Animation" ],
        [ "Bonus", "structrtype_1_1components_1_1Bonus.html", "structrtype_1_1components_1_1Bonus" ],
        [ "ChildEntities", "structrtype_1_1components_1_1ChildEntities.html", "structrtype_1_1components_1_1ChildEntities" ],
        [ "Counter", "structrtype_1_1components_1_1Counter.html", "structrtype_1_1components_1_1Counter" ],
        [ "Created", "structrtype_1_1components_1_1Created.html", "structrtype_1_1components_1_1Created" ],
        [ "Damage", "structrtype_1_1components_1_1Damage.html", "structrtype_1_1components_1_1Damage" ],
        [ "EventId", "structrtype_1_1components_1_1EventId.html", "structrtype_1_1components_1_1EventId" ],
        [ "GameState", "structrtype_1_1components_1_1GameState.html", "structrtype_1_1components_1_1GameState" ],
        [ "Health", "structrtype_1_1components_1_1Health.html", "structrtype_1_1components_1_1Health" ],
        [ "Hitbox", "structrtype_1_1components_1_1Hitbox.html", "structrtype_1_1components_1_1Hitbox" ],
        [ "IA", "structrtype_1_1components_1_1IA.html", "structrtype_1_1components_1_1IA" ],
        [ "InputHandler", "structrtype_1_1components_1_1InputHandler.html", "structrtype_1_1components_1_1InputHandler" ],
        [ "MenuState", "structrtype_1_1components_1_1MenuState.html", "structrtype_1_1components_1_1MenuState" ],
        [ "Music", "structrtype_1_1components_1_1Music.html", "structrtype_1_1components_1_1Music" ],
        [ "NetId", "structrtype_1_1components_1_1NetId.html", "structrtype_1_1components_1_1NetId" ],
        [ "NetworkConnection", "structrtype_1_1components_1_1NetworkConnection.html", "structrtype_1_1components_1_1NetworkConnection" ],
        [ "NoDamageToPlayer", "structrtype_1_1components_1_1NoDamageToPlayer.html", "structrtype_1_1components_1_1NoDamageToPlayer" ],
        [ "OnClick", "structrtype_1_1components_1_1OnClick.html", "structrtype_1_1components_1_1OnClick" ],
        [ "ParentEntity", "structrtype_1_1components_1_1ParentEntity.html", "structrtype_1_1components_1_1ParentEntity" ],
        [ "PlayerBonuses", "structrtype_1_1components_1_1PlayerBonuses.html", "structrtype_1_1components_1_1PlayerBonuses" ],
        [ "Position", "structrtype_1_1components_1_1Position.html", "structrtype_1_1components_1_1Position" ],
        [ "Projectile", "structrtype_1_1components_1_1Projectile.html", "structrtype_1_1components_1_1Projectile" ],
        [ "ProjectileInfo", "structrtype_1_1components_1_1ProjectileInfo.html", "structrtype_1_1components_1_1ProjectileInfo" ],
        [ "Running", "structrtype_1_1components_1_1Running.html", "structrtype_1_1components_1_1Running" ],
        [ "SfText", "structrtype_1_1components_1_1SfText.html", "structrtype_1_1components_1_1SfText" ],
        [ "Size", "structrtype_1_1components_1_1Size.html", "structrtype_1_1components_1_1Size" ],
        [ "SlidingBg", "structrtype_1_1components_1_1SlidingBg.html", "structrtype_1_1components_1_1SlidingBg" ],
        [ "Sound", "structrtype_1_1components_1_1Sound.html", "structrtype_1_1components_1_1Sound" ],
        [ "Speed", "structrtype_1_1components_1_1Speed.html", "structrtype_1_1components_1_1Speed" ],
        [ "Sprite", "structrtype_1_1components_1_1Sprite.html", "structrtype_1_1components_1_1Sprite" ],
        [ "String", "structrtype_1_1components_1_1String.html", "structrtype_1_1components_1_1String" ],
        [ "Velocity", "structrtype_1_1components_1_1Velocity.html", "structrtype_1_1components_1_1Velocity" ],
        [ "ZIndex", "structrtype_1_1components_1_1ZIndex.html", "structrtype_1_1components_1_1ZIndex" ]
      ] ],
      [ "ecs", "namespacertype_1_1ecs.html", [
        [ "AEntity", "classrtype_1_1ecs_1_1AEntity.html", "classrtype_1_1ecs_1_1AEntity" ],
        [ "AScene", "classrtype_1_1ecs_1_1AScene.html", "classrtype_1_1ecs_1_1AScene" ],
        [ "ComponentManager", "classrtype_1_1ecs_1_1ComponentManager.html", "classrtype_1_1ecs_1_1ComponentManager" ],
        [ "Entity", "structrtype_1_1ecs_1_1Entity.html", "structrtype_1_1ecs_1_1Entity" ],
        [ "EntityManager", "classrtype_1_1ecs_1_1EntityManager.html", "classrtype_1_1ecs_1_1EntityManager" ],
        [ "IEntity", "classrtype_1_1ecs_1_1IEntity.html", "classrtype_1_1ecs_1_1IEntity" ],
        [ "IScene", "classrtype_1_1ecs_1_1IScene.html", "classrtype_1_1ecs_1_1IScene" ],
        [ "ISparseSet", "classrtype_1_1ecs_1_1ISparseSet.html", "classrtype_1_1ecs_1_1ISparseSet" ],
        [ "SceneManager", "classrtype_1_1ecs_1_1SceneManager.html", "classrtype_1_1ecs_1_1SceneManager" ],
        [ "SparseSet", "classrtype_1_1ecs_1_1SparseSet.html", "classrtype_1_1ecs_1_1SparseSet" ],
        [ "SystemManager", "classrtype_1_1ecs_1_1SystemManager.html", "classrtype_1_1ecs_1_1SystemManager" ]
      ] ],
      [ "entities", "namespacertype_1_1entities.html", [
        [ "BossAlien", "classrtype_1_1entities_1_1BossAlien.html", "classrtype_1_1entities_1_1BossAlien" ],
        [ "BossCask", "classrtype_1_1entities_1_1BossCask.html", "classrtype_1_1entities_1_1BossCask" ],
        [ "BossDarkplayer", "classrtype_1_1entities_1_1BossDarkplayer.html", "classrtype_1_1entities_1_1BossDarkplayer" ],
        [ "BossHeart", "classrtype_1_1entities_1_1BossHeart.html", "classrtype_1_1entities_1_1BossHeart" ],
        [ "BossMachin", "classrtype_1_1entities_1_1BossMachin.html", "classrtype_1_1entities_1_1BossMachin" ],
        [ "BossRobot", "classrtype_1_1entities_1_1BossRobot.html", "classrtype_1_1entities_1_1BossRobot" ],
        [ "BossStaros", "classrtype_1_1entities_1_1BossStaros.html", "classrtype_1_1entities_1_1BossStaros" ],
        [ "BossTurret", "classrtype_1_1entities_1_1BossTurret.html", "classrtype_1_1entities_1_1BossTurret" ],
        [ "Button", "classrtype_1_1entities_1_1Button.html", "classrtype_1_1entities_1_1Button" ],
        [ "Enemy", "classrtype_1_1entities_1_1Enemy.html", "classrtype_1_1entities_1_1Enemy" ],
        [ "EnemyCornus", "classrtype_1_1entities_1_1EnemyCornus.html", "classrtype_1_1entities_1_1EnemyCornus" ],
        [ "EnemyCrabus", "classrtype_1_1entities_1_1EnemyCrabus.html", "classrtype_1_1entities_1_1EnemyCrabus" ],
        [ "EnemyPablitos", "classrtype_1_1entities_1_1EnemyPablitos.html", "classrtype_1_1entities_1_1EnemyPablitos" ],
        [ "Game", "classrtype_1_1entities_1_1Game.html", "classrtype_1_1entities_1_1Game" ],
        [ "Image", "classrtype_1_1entities_1_1Image.html", "classrtype_1_1entities_1_1Image" ],
        [ "Mode", "structrtype_1_1entities_1_1Mode.html", "structrtype_1_1entities_1_1Mode" ],
        [ "Player", "classrtype_1_1entities_1_1Player.html", "classrtype_1_1entities_1_1Player" ],
        [ "PlayerCounter", "classrtype_1_1entities_1_1PlayerCounter.html", "classrtype_1_1entities_1_1PlayerCounter" ],
        [ "RWindow", "structrtype_1_1entities_1_1RWindow.html", "structrtype_1_1entities_1_1RWindow" ],
        [ "Style", "structrtype_1_1entities_1_1Style.html", "structrtype_1_1entities_1_1Style" ],
        [ "Window", "classrtype_1_1entities_1_1Window.html", "classrtype_1_1entities_1_1Window" ]
      ] ],
      [ "levels", "namespacertype_1_1levels.html", [
        [ "Level", "classrtype_1_1levels_1_1Level.html", "classrtype_1_1levels_1_1Level" ],
        [ "LevelBuilder", "classrtype_1_1levels_1_1LevelBuilder.html", "classrtype_1_1levels_1_1LevelBuilder" ],
        [ "LevelManager", "classrtype_1_1levels_1_1LevelManager.html", "classrtype_1_1levels_1_1LevelManager" ]
      ] ],
      [ "models", "namespacertype_1_1models.html", [
        [ "BonusData", "structrtype_1_1models_1_1BonusData.html", "structrtype_1_1models_1_1BonusData" ],
        [ "EnemyData", "structrtype_1_1models_1_1EnemyData.html", "structrtype_1_1models_1_1EnemyData" ],
        [ "EnemySpawn", "structrtype_1_1models_1_1EnemySpawn.html", "structrtype_1_1models_1_1EnemySpawn" ],
        [ "PlayerData", "structrtype_1_1models_1_1PlayerData.html", "structrtype_1_1models_1_1PlayerData" ],
        [ "ProjectileData", "structrtype_1_1models_1_1ProjectileData.html", "structrtype_1_1models_1_1ProjectileData" ],
        [ "Scene", "structrtype_1_1models_1_1Scene.html", "structrtype_1_1models_1_1Scene" ],
        [ "SpawnPoint", "structrtype_1_1models_1_1SpawnPoint.html", "structrtype_1_1models_1_1SpawnPoint" ]
      ] ],
      [ "network", "namespacertype_1_1network.html", [
        [ "APacket", "classrtype_1_1network_1_1APacket.html", "classrtype_1_1network_1_1APacket" ],
        [ "IPacket", "classrtype_1_1network_1_1IPacket.html", "classrtype_1_1network_1_1IPacket" ],
        [ "PacketBonus", "classrtype_1_1network_1_1PacketBonus.html", "classrtype_1_1network_1_1PacketBonus" ],
        [ "PacketConnect", "classrtype_1_1network_1_1PacketConnect.html", "classrtype_1_1network_1_1PacketConnect" ],
        [ "PacketEndGame", "classrtype_1_1network_1_1PacketEndGame.html", "classrtype_1_1network_1_1PacketEndGame" ],
        [ "PacketEnemiesData", "classrtype_1_1network_1_1PacketEnemiesData.html", "classrtype_1_1network_1_1PacketEnemiesData" ],
        [ "PacketFactory", "classrtype_1_1network_1_1PacketFactory.html", "classrtype_1_1network_1_1PacketFactory" ],
        [ "PacketLevelsRegistered", "classrtype_1_1network_1_1PacketLevelsRegistered.html", "classrtype_1_1network_1_1PacketLevelsRegistered" ],
        [ "PacketPlayerCounter", "classrtype_1_1network_1_1PacketPlayerCounter.html", "classrtype_1_1network_1_1PacketPlayerCounter" ],
        [ "PacketPlayersData", "classrtype_1_1network_1_1PacketPlayersData.html", "classrtype_1_1network_1_1PacketPlayersData" ],
        [ "PacketPlayerShoot", "classrtype_1_1network_1_1PacketPlayerShoot.html", "classrtype_1_1network_1_1PacketPlayerShoot" ],
        [ "PacketStartGame", "classrtype_1_1network_1_1PacketStartGame.html", "classrtype_1_1network_1_1PacketStartGame" ],
        [ "PacketWelcome", "classrtype_1_1network_1_1PacketWelcome.html", "classrtype_1_1network_1_1PacketWelcome" ],
        [ "TCPNetwork", "classrtype_1_1network_1_1TCPNetwork.html", "classrtype_1_1network_1_1TCPNetwork" ],
        [ "UDPNetwork", "classrtype_1_1network_1_1UDPNetwork.html", "classrtype_1_1network_1_1UDPNetwork" ]
      ] ],
      [ "scenes", "namespacertype_1_1scenes.html", [
        [ "Game", "classrtype_1_1scenes_1_1Game.html", "classrtype_1_1scenes_1_1Game" ],
        [ "Lose", "classrtype_1_1scenes_1_1Lose.html", "classrtype_1_1scenes_1_1Lose" ],
        [ "Menu", "classrtype_1_1scenes_1_1Menu.html", "classrtype_1_1scenes_1_1Menu" ],
        [ "Win", "classrtype_1_1scenes_1_1Win.html", "classrtype_1_1scenes_1_1Win" ]
      ] ],
      [ "services", "namespacertype_1_1services.html", [
        [ "BonusService", "classrtype_1_1services_1_1BonusService.html", null ],
        [ "EnemyService", "classrtype_1_1services_1_1EnemyService.html", null ],
        [ "PlayerService", "classrtype_1_1services_1_1PlayerService.html", null ],
        [ "ProjectileService", "classrtype_1_1services_1_1ProjectileService.html", null ]
      ] ],
      [ "systems", "namespacertype_1_1systems.html", [
        [ "ANetworkHandler", "classrtype_1_1systems_1_1ANetworkHandler.html", "classrtype_1_1systems_1_1ANetworkHandler" ],
        [ "BonusHandler", "classrtype_1_1systems_1_1BonusHandler.html", "classrtype_1_1systems_1_1BonusHandler" ],
        [ "ConnectHandler", "classrtype_1_1systems_1_1ConnectHandler.html", "classrtype_1_1systems_1_1ConnectHandler" ],
        [ "EndGameHandler", "classrtype_1_1systems_1_1EndGameHandler.html", "classrtype_1_1systems_1_1EndGameHandler" ],
        [ "EnnemiesDataHandler", "classrtype_1_1systems_1_1EnnemiesDataHandler.html", "classrtype_1_1systems_1_1EnnemiesDataHandler" ],
        [ "INetworkHandler", "classrtype_1_1systems_1_1INetworkHandler.html", "classrtype_1_1systems_1_1INetworkHandler" ],
        [ "InputSystem", "classrtype_1_1systems_1_1InputSystem.html", null ],
        [ "LevelRunner", "classrtype_1_1systems_1_1LevelRunner.html", null ],
        [ "LevelsRegisteredHandler", "classrtype_1_1systems_1_1LevelsRegisteredHandler.html", "classrtype_1_1systems_1_1LevelsRegisteredHandler" ],
        [ "Movement", "classrtype_1_1systems_1_1Movement.html", "classrtype_1_1systems_1_1Movement" ],
        [ "Network", "classrtype_1_1systems_1_1Network.html", null ],
        [ "PlayerCountHandler", "classrtype_1_1systems_1_1PlayerCountHandler.html", "classrtype_1_1systems_1_1PlayerCountHandler" ],
        [ "PlayerDataHandler", "classrtype_1_1systems_1_1PlayerDataHandler.html", "classrtype_1_1systems_1_1PlayerDataHandler" ],
        [ "PlayerShootHandler", "classrtype_1_1systems_1_1PlayerShootHandler.html", "classrtype_1_1systems_1_1PlayerShootHandler" ],
        [ "RenderWindowSys", "classrtype_1_1systems_1_1RenderWindowSys.html", null ],
        [ "Sound", "classrtype_1_1systems_1_1Sound.html", null ],
        [ "StartGameHandler", "classrtype_1_1systems_1_1StartGameHandler.html", "classrtype_1_1systems_1_1StartGameHandler" ],
        [ "UpdateProjectilesSystem", "classrtype_1_1systems_1_1UpdateProjectilesSystem.html", null ],
        [ "WelcomeHandler", "classrtype_1_1systems_1_1WelcomeHandler.html", "classrtype_1_1systems_1_1WelcomeHandler" ]
      ] ],
      [ "Config", "classrtype_1_1Config.html", "classrtype_1_1Config" ],
      [ "ModeManager", "classrtype_1_1ModeManager.html", null ],
      [ "RType", "classrtype_1_1RType.html", null ],
      [ "TextureManager", "classrtype_1_1TextureManager.html", "classrtype_1_1TextureManager" ],
      [ "ThreadPool", "classrtype_1_1ThreadPool.html", "classrtype_1_1ThreadPool" ]
    ] ],
    [ "ComponentManager", "classComponentManager.html", null ],
    [ "EntityManager", "classEntityManager.html", null ],
    [ "Player", "classPlayer.html", null ],
    [ "SoundSys", "classSoundSys.html", null ],
    [ "SparseSet", "classSparseSet.html", null ],
    [ "SystemManager", "classSystemManager.html", null ]
];