name: "R-Type CI"

on:
  push:

jobs:
  build:
    name: "Build"
    uses: "./.github/workflows/build.yml"
    with:
      EXECUTABLES: "r-type_server,r-type_client"

  common:
    name: "Common"
    needs:
      - "build"
    uses: "./.github/workflows/mirror.yml"
    secrets: inherit
